project:
  type: website
  output-dir: docs
  execute-dir: project

website:
  title: "CSB Ecuador"
  repo-url: https://github.com/rvconsulting/cta-bioeconomia-ECU/
#  issue-url: https://github.com/rvconsulting/cta-bioeconomia-ECU/issues
  repo-actions: [source]
  repo-branch: master
  navbar:
    pinned: true
    left:
      - href: index.qmd
        text: Home
      - acerca.qmd
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Reportes"
        contents: reportes/*
      - section: "Material Suplementario"
        contents: suplementarios/*
      # - section: "Dashboards"
      #   contents: dashboards/*

# editor_options: 
#   chunk_output_type: console
  
format:
  html:
    theme: yeti
    css: styles.css
    toc: true

editor: source